#
# Deploy Docker Repository Pull Secrets
#

#
# Helm Defaults
# 
helmDefaults:
  wait: true
  verify: false
  timeout: 600
  recreatePods: false
  force: true

repositories:
  # Cloud Posse incubator repo of helm charts
  - name: "cloudposse-incubator"
    url: "https://charts.cloudposse.com/incubator/"
#
# Kubernetes cluster
#
context: '{{ requiredEnv "KUBE_CONTEXT" }}'

#
# Helm Releases
#
releases:
  # Pull Secret (.dockercfg)
  - name: '{{ requiredEnv "RELEASE_NAME" }}-pull-secret'
    chart: "cloudposse-incubator/dockercfg"
    version: "0.1.0"
    namespace: '{{ requiredEnv "NAMESPACE" }}'
    labels:
      chart: "dockercfg"
      component: "secrets"
      preview: "true"

    values:
    - image:
        pullSecret:
          registry: '{{ requiredEnv "IMAGE_PULL_SECRET_REGISTRY" }}'
          username: '{{ requiredEnv "IMAGE_PULL_SECRET_USERNAME" }}'
          password: '{{ requiredEnv "IMAGE_PULL_SECRET_PASSWORD" }}'
