version: '1.0'

stages:
  - Prepare
  - Deploy

steps:
  main_clone:
    title: "Create Context"
    stage: Prepare
    image: alpine
    commands:
    - cf_export NAMESPACE=${{STAGE}}
    - cf_export IMAGE_NAME=${{CF_DOCKER_REPO_URL}}/${{CF_REPO_NAME}}
    - cf_export IMAGE_TAG=${{CF_RELEASE_TAG}}
    - cf_export GATEWAY_HOST=example.${{BASE_HOST}}

  deploy_helmfile:
    title: "Deploy with helmfile"
    stage: "Deploy"
    image: "${{CF_DOCKER_REPO_URL}}/${{CF_REPO_NAME}}:${{CF_REVISION}}"
    working_directory: /deploy/
    commands:
    # Announce the release version
    - "echo 'Preparing to deploy ${{CF_REPO_NAME}}:${{CF_RELEASE_TAG}}'"
    # Deploy chart to cluster
    - "/deploy/ctl --namespace=${{NAMESPACE}} blue-green"

