version: '1.0'

stages:
- Destroy

steps:
  main_clone:
    title: Wait
    stage: Prepare
    image: codefresh/cli:latest
    commands:
      - codefresh get builds --pipeline=pull-request --status running --limit 1000 -o json | jq --arg id ${{CF_BUILD_ID}} -ser 'flatten|.[-1].id==$id'
    retry:
      maxAttempts: 10
      delay: 20
      exponentialFactor: 1.1
    when:
      condition:
        any:
          deployLabel: "match('${{CF_PULL_REQUEST_LABELS}}', 'deploy', false) == false"
          validatePRAction: "'${{CF_PULL_REQUEST_ACTION}}' == 'closed'"

  destroy:
    title: Destroy namespace
    stage: Destroy
    image: cloudposse/build-harness:${{BUILD_HARNESS_VERSION}}
    working_directory: /build-harness/
    environment:
    - NAMESPACE=pr-${{CF_PULL_REQUEST_NUMBER}}-${{CF_REPO_NAME}}
    commands:
    - "apk add kubectl"
    - "kubectl config use-context ${{KUBE_CONTEXT}}"
    - "make helm/delete/namespace"
    - "make helm/delete/namespace/empty"
    when:
      condition:
        any:
          deployLabel: "match('${{CF_PULL_REQUEST_LABELS}}', 'deploy', false) == false"
          validatePRAction: "'${{CF_PULL_REQUEST_ACTION}}' == 'closed'"

