name: Reusable - Bleeding edge
on:
  workflow_call:
    inputs:
      organization:
        required: true
        type: string
      repository:
        required: true
        type: string
      registry:
        description: "Docker registry"
        required: false
        type: string
        default: registry.hub.docker.com
    secrets:
      docker-login:
        required: true
      docker-password:
        required: true
      github-private-actions-pat:
        required: true

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false


jobs:
  build:
    runs-on: ["self-hosted"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout Private actions
        uses: actions/checkout@v3
        with:
          repository: cloudposse/actions-private
          ref: main
          token: ${{ secrets.github-private-actions-pat }}
          path: .github/actions

      - name: Build
        id: build
        uses: ./.github/actions/build
        with:
          organization: ${{ inputs.organization }}
          repository: ${{ inputs.repository }}
          registry: ${{ inputs.registry }}
          login: ${{ secrets.docker-login }}
          password: ${{ secrets.docker-password }}

    outputs:
      image: ${{ steps.build.outputs.image }}
      tag: ${{ steps.build.outputs.tag }}

  test:
    runs-on: ["self-hosted"]
    needs: [ build ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout Private actions
        uses: actions/checkout@v3
        with:
          repository: cloudposse/actions-private
          ref: main
          token: ${{ secrets.github-private-actions-pat }}
          path: .github/actions

      - name: Tests
        id: test
        uses: ./.github/actions/docker-compose-tests-run
        with:
          file: codefresh/test/docker-compose.yml
          service: app
          command: codefresh/test/test.sh

  semver:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - name: Create/Update Draft release
        uses: release-drafter/release-drafter@v5
        with:
          publish: false
          prerelease: false
          config-name: configs/draft-release.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ["self-hosted"]
    environment:
      name: dev
      url: ${{ steps.deploy.outputs.webapp-url }}
    needs: [ build, test ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout Private actions
        uses: actions/checkout@v3
        with:
          repository: cloudposse/actions-private
          ref: main
          token: ${{ secrets.github-private-actions-pat }}
          path: .github/actions

      - name: Environment Info
        uses: ./.github/actions/environments
        id: environment
        with:
          environment: dev
          namespace: dev

      - name: Deploy
        uses: ./.github/actions/deploy
        id: deploy
        with:
          aws-region: ${{ steps.environment.outputs.region }}
          base-role: ${{ steps.environment.outputs.role }}
          cluster: ${{ steps.environment.outputs.cluster }}
          cluster-role: ${{ steps.environment.outputs.cluster-role }}
          environment: ${{ steps.environment.outputs.name }}
          namespace: ${{ steps.environment.outputs.namespace }}
          image: ${{ needs.build.outputs.image }}
          image-tag: ${{ needs.build.outputs.tag }}
          operation: deploy
